## Let's get the domains for the entire tree and plot them

In [1]:
from collections import defaultdict  # LP: required for parsing the domain data
from pathlib import Path

# We'll need ETE3 to parse and render the tree
from ete3 import Tree, TreeStyle, NodeStyle, TextFace, CircleFace, faces, SeqMotifFace
from tqdm.notebook import tqdm
import pandas as pd

In [2]:
# File locations and other constants
treepath = Path("TBE_named_tree_manual.new")  # transporter family tree, Newick format
annopath = Path("annotations.csv")     # annotations for some family members

In [3]:
# Load the tree and, for convenience, root it to the midpoint
# We have these as functions so that we can annotate/render a clean tree each time
def load_tree():
    tree = Tree(str(treepath))
    # midpoint = tree.get_midpoint_outgroup()  # Calculate the midpoint node
    # tree.set_outgroup(midpoint)# and set it as tree outgroup
    # tree.ladderize()
    return tree

# Load the annotation
def load_annotation():
    anno = pd.read_csv(annopath)
    return anno

In [4]:
load_annotation()  # Load the unaltered annotation as it is in the file

              id   kingdom match
0     A0A556RIY8  Bacteria   NaN
1         K8W564  Bacteria   NaN
2     A0AA87CRL5  Bacteria   NaN
3         B6XEC6  Bacteria   NaN
4         K8X885  Bacteria   NaN
...          ...       ...   ...
1671  A0A7R6P982  Bacteria   NaN
1672  A0A7R6PDR3  Bacteria   NaN
1673  A0A7U8C906  Bacteria   NaN
1674  A0A2G6JCW0  Bacteria   NaN
1675  A0A066ZX21  Bacteria   NaN

[1676 rows x 3 columns]

In [5]:
# The function lets us return the tree and its corresponding annotation,
# where the leaves of this specific tree object are present in the
# annotation dataframe, and so can be manipulated easily.
def annotate_tree():
    tree = load_tree()
    anno = load_annotation()
    
    leaves = []  # Will hold leaves for the tree where they match the annotation row, or None if there is none
    
    for id in anno["id"]:               # iterate over annotations
        for leaf in tree.iter_leaves():  # iterate over all leaves in the tree
            assigned = False
            if id in str(leaf):
                leaves.append(leaf)
                assigned = True
                break
        if not assigned:
            leaves.append(None)
    
    anno["leaves"] = leaves

    return tree, anno

In [6]:
tree, anno = annotate_tree()  # get the annotated tree
anno

,id,kingdom,match,leaves
0,A0A556RIY8,Bacteria,NaN,(((\n--Gilliamella apicola Nitrogen regulatory...
1,K8W564,Bacteria,NaN,(((\n--Providencia sneebia DSM 19967 Nitrogen ...
2,A0AA87CRL5,Bacteria,NaN,(((\n--Providencia stuartii ATCC 25827 Nitroge...
3,B6XEC6,Bacteria,NaN,(((\n--Providencia alcalifaciens DSM 30120 Nit...
4,K8X885,Bacteria,NaN,(((\n--Providencia burhodogranariea DSM 19968 ...
...,...,...,...,...
1671,A0A7R6P982,Bacteria,NaN,(((\n--Neptunomonas japonica JAMM 1380 Nitroge...
1672,A0A7R6PDR3,Bacteria,NaN,(((\n--Neptunomonas japonica JAMM 1380 Nitroge...
1673,A0A7U8C906,Bacteria,NaN,(((\n--Neptuniibacter caesariensis Regulatory ...
1674,A0A2G6JCW0,Bacteria,NaN,(((\n--Neptuniibacter caesariensis Transcripti...
1675,A0A066ZX21,Bacteria,NaN,(((\n--Hydrogenovibrio marinus Nitrogen regula...

In [26]:
tree, anno = annotate_tree()  # get a clean tree

# Declare a style (we could have put this in a function to save repeated code)
kingdom = TreeStyle()
kingdom.show_leaf_name = True
kingdom.mode = "c"
kingdom.show_branch_support = True

tree.ladderize()
R = tree.get_midpoint_outgroup()
tree.set_outgroup(R)

# One text face for each kingdom
face_dict = {"Eukaryota": TextFace("eukaryota"),
             "Bacteria": TextFace("bacteria"),
             "Archaea": TextFace("archaea")}

# Set colours for kingdoms
colour_dict = {"Eukarya": "#FFFACD", "Bacteria": "#F0F8FF", "Archaea": "#FFE4E1"}

# Iterate over all annotated leaves and add the face
for idx, row in anno.iterrows():
    # Get annotation information
    leaf = row["leaves"]
    kingdomname = row["kingdom"]


    # Set styling for the leaf node
    # leaf.img_style["size"] = 12
    if kingdomname in ("Eukarya", "Bacteria", "Archaea"):
        leaf.img_style["bgcolor"] = colour_dict[kingdomname]    
        leaf.add_face(face_dict[kingdomname], 0, "aligned")

tree.render("figure_3.6.pdf", tree_style=kingdom, w=24, h=24, units="in");

In [5]:
my_file = open("domain_info.txt", "r") 
  
# reading the file 
dat = my_file.read() 
  
# replacing end splitting the text  
# when newline ('\n') is seen. 
domain_info = dat.split("\n") 
print(domain_info) 
my_file.close()

["Q8GQS1: Ammonium Transporter Family [{'start': 50, 'end': 460, 'dc-status': 'CONTINUOUS'}] 463", "A0A401X433: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 465", "A0AAC9SUX5: Ammonium Transporter Family [{'start': 45, 'end': 455, 'dc-status': 'CONTINUOUS'}] 459", "F1YU33: Ammonium Transporter Family [{'start': 52, 'end': 462, 'dc-status': 'CONTINUOUS'}] 466", "A0A1D8QW75: Ammonium Transporter Family [{'start': 52, 'end': 462, 'dc-status': 'CONTINUOUS'}] 466", "A0A401WUW1: Ammonium Transporter Family [{'start': 52, 'end': 462, 'dc-status': 'CONTINUOUS'}] 466", "A0A1Y0UZX2: Ammonium Transporter Family [{'start': 43, 'end': 453, 'dc-status': 'CONTINUOUS'}] 457", "A0A291PMC6: Ammonium Transporter Family [{'start': 37, 'end': 447, 'dc-status': 'CONTINUOUS'}] 450", "A0A0U5EV31: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 464", "A0A149U2G9: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 464", "F7VFV0: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 464", "A0A149QAW7: Ammonium Transporter Family [{'start': 52, 'end': 462, 'dc-status': 'CONTINUOUS'}] 465", "A0A149UWF2: Ammonium Transporter Family [{'start': 52, 'end': 462, 'dc-status': 'CONTINUOUS'}] 465", "A0AAN1PKE9: Ammonium Transporter Family [{'start': 32, 'end': 442, 'dc-status': 'CONTINUOUS'}] 446", "A0A1A0CF26: Ammonium Transporter Family [{'start': 45, 'end': 455, 'dc-status': 'CONTINUOUS'}] 459", "A0A149TSA9: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 464", "A0A095B4M5: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 464", "A0A511FKZ2: Ammonium Transporter Family [{'start': 51, 'end': 461, 'dc-status': 'CONTINUOUS'}] 464", "A0A252A952: Ammonium Transporter Family [{'start': 37, 'end': 447, 'dc-status': 'CONTINUOUS'}] 450", "A0A149V963: Ammonium Transporter Family [{'start': 24, 'end': 434, 'dc-status': 'CONTINUOUS'}] 437", "A0A1D8UWJ6: Ammonium Transporter Family [{'start': 33, 'end': 443, 'dc-status': 'CONTINUOUS'}] 446", "A0A4Y1MSE7: Ammonium Transporter Family [{'start': 54, 'end': 459, 'dc-status': 'CONTINUOUS'}] 462", "A0A1S8D478: Ammonium Transporter Family [{'start': 31, 'end': 436, 'dc-status': 'CONTINUOUS'}] 439", "F3QNA7: Ammonium Transporter Family [{'start': 30, 'end': 418, 'dc-status': 'CONTINUOUS'}] 420", "G0JRH4: Ammonium Transporter Family [{'start': 41, 'end': 437, 'dc-status': 'CONTINUOUS'}] 438", "A0A1B9BUZ8: Ammonium Transporter Family [{'start': 41, 'end': 437, 'dc-status': 'CONTINUOUS'}] 438", "A0A060URB8: Ammonium Transporter Family [{'start': 41, 'end': 437, 'dc-status': 'CONTINUOUS'}] 438", "A0AAN0VNJ0: Ammonium Transporter Family [{'start': 105, 'end': 500, 'dc-status': 'CONTINUOUS'}] 502", "B1JZ69: Ammonium Transporter Family [{'start': 103, 'end': 498, 'dc-status': 'CONTINUOUS'}] 500", "A0A0H2XSU4: Ammonium Transporter Family [{'start': 103, 'end': 498, 'dc-status': 'CONTINUOUS'}] 500", "A0A071MMV1: Ammonium Transporter Family [{'start': 106, 'end': 501, 'dc-status': 'CONTINUOUS'}] 503", "A0A6J5IRX5: Ammonium Transporter Family [{'start': 107, 'end': 502, 'dc-status': 'CONTINUOUS'}] 504", "A0A3S9N9F3: Ammonium Transporter Family [{'start': 108, 'end': 503, 'dc-status': 'CONTINUOUS'}] 505", "A0A1T4SFK4: Ammonium Transporter Family [{'start': 40, 'end': 440, 'dc-status': 'CONTINUOUS'}] 442", "A0A1T4SF40: Ammonium Transporter Family [{'start': 39, 'end': 434, 'dc-status': 'CONTINUOUS'}] 436", "A0A2W5HTC3: Ammonium Transporter Family [{'start': 37, 'end': 444, 'dc-status': 'CONTINUOUS'}] 446", "W0DZS7: Ammonium Transporter Family [{'start': 39, 'end': 436, 'dc-status': 'CONTINUOUS'}] 438", "B4CV94: Ammonium Transporter Family [{'start': 56, 'end': 483, 'dc-status': 'CONTINUOUS'}] 484", "C1MX19: Ammonium Transporter Family [{'start': 141, 'end': 536, 'dc-status': 'CONTINUOUS'}] 561", "A0A2S0P9T4: Ammonium Transporter Family [{'start': 75, 'end': 462, 'dc-status': 'CONTINUOUS'}] 465", "A0A060HN92: Ammonium Transporter Family [{'start': 10, 'end': 406, 'dc-status': 'CONTINUOUS'}] 408", "Q2IHY5: Ammonium Transporter Family [{'start': 29, 'end': 424, 'dc-status': 'CONTINUOUS'}] 456", "A0A017SYR8: Ammonium Transporter Family [{'start': 9, 'end': 402, 'dc-status': 'CONTINUOUS'}] 404", "A0A068NPW2: Ammonium Transporter Family [{'start': 38, 'end': 442, 'dc-status': 'CONTINUOUS'}] 444", "A0A0E3SP24: Ammonium Transporter Family [{'start': 9, 'end': 395, 'dc-status': 'CONTINUOUS'}] 397", "A0A0E3R6E1: Ammonium Transporter Family [{'start': 9, 'end': 395, 'dc-status': 'CONTINUOUS'}] 397", "A0A0E3QKN0: Ammonium Transporter Family [{'start': 9, 'end': 395, 'dc-status': 'CONTINUOUS'}] 397", "A0A410JZR4: Ammonium Transporter Family [{'start': 29, 'end': 415, 'dc-status': 'CONTINUOUS'}] 419", "Q3AP28: Ammonium Transporter Family [{'start': 37, 'end': 438, 'dc-status': 'CONTINUOUS'}] 444", "Q1JXS5: Ammonium Transporter Family [{'start': 32, 'end': 432, 'dc-status': 'CONTINUOUS'}] 441", "A0A1M6JKY3: Ammonium Transporter Family [{'start': 34, 'end': 433, 'dc-status': 'CONTINUOUS'}] 436", "B8FGW0: Ammonium Transporter Family [{'start': 34, 'end': 433, 'dc-status': 'CONTINUOUS'}] 436", "P41948: Ammonium Transporter Family [{'start': 34, 'end': 444, 'dc-status': 'CONTINUOUS'}] 499", "P40260: Ammonium Transporter Family [{'start': 20, 'end': 424, 'dc-status': 'CONTINUOUS'}] 492", "P92962: Transmembrane amino acid transporter protein [{'start': 31, 'end': 423, 'dc-status': 'CONTINUOUS'}] 439", "P92961: Transmembrane amino acid transporter protein [{'start': 34, 'end': 426, 'dc-status': 'CONTINUOUS'}] 442", "C8V329: Permease for cytosine/purines, uracil, thiamine, allantoin [{'start': 60, 'end': 471, 'dc-status': 'CONTINUOUS'}] 508", "Q9UPI3: Major Facilitator Superfamily [{'start': 95, 'end': 453, 'dc-status': 'CONTINUOUS'}] 526", "Q9Y5Y0: Major Facilitator Superfamily [{'start': 116, 'end': 477, 'dc-status': 'CONTINUOUS'}] 555", "P19807: Amino acid permease [{'start': 58, 'end': 501, 'dc-status': 'CONTINUOUS'}] 563", "Q96247: Transmembrane amino acid transporter protein [{'start': 44, 'end': 437, 'dc-status': 'CONTINUOUS'}] 485", "G5EB09: Ammonium Transporter Family [{'start': 53, 'end': 458, 'dc-status': 'CONTINUOUS'}] 544", "A0A0A2VPU3: Ammonium Transporter Family [{'start': 36, 'end': 440, 'dc-status': 'CONTINUOUS'}] 471", "G5EB13: Ammonium Transporter Family [{'start': 33, 'end': 438, 'dc-status': 'CONTINUOUS'}] 478", "D2BIB2: Ammonium Transporter Family [{'start': 8, 'end': 403, 'dc-status': 'CONTINUOUS'}] 408", "Q3Z7F9: Ammonium Transporter Family [{'start': 8, 'end': 403, 'dc-status': 'CONTINUOUS'}] 408", "A0A328EMN2: Ammonium Transporter Family [{'start': 8, 'end': 403, 'dc-status': 'CONTINUOUS'}] 408", "A0A916NVE1: Ammonium Transporter Family [{'start': 8, 'end': 403, 'dc-status': 'CONTINUOUS'}] 408", "A0A075WEB4: Ammonium Transporter Family [{'start': 8, 'end': 387, 'dc-status': 'CONTINUOUS'}] 388", "A0A075WBP9: Ammonium Transporter Family [{'start': 7, 'end': 390, 'dc-status': 'CONTINUOUS'}] 391", "A0A8F5ZDT8: Ammonium Transporter Family [{'start': 9, 'end': 395, 'dc-status': 'CONTINUOUS'}] 397", "Q2FS34: Ammonium Transporter Family [{'start': 9, 'end': 395, 'dc-status': 'CONTINUOUS'}] 397", "J1L5M8: Ammonium Transporter Family [{'start': 12, 'end': 398, 'dc-status': 'CONTINUOUS'}] 401", "A0A8F5VN39: Ammonium Transporter Family [{'start': 7, 'end': 394, 'dc-status': 'CONTINUOUS'}] 396", "Q2FQT3: Ammonium Transporter Family [{'start': 7, 'end': 393, 'dc-status': 'CONTINUOUS'}] 396", "J1ASR8: Ammonium Transporter Family [{'start': 9, 'end': 396, 'dc-status': 'CONTINUOUS'}] 398", "F8IJE0: Ammonium Transporter Family [{'start': 28, 'end': 426, 'dc-status': 'CONTINUOUS'}] 458", "C8WLL8: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "A0A5C5BWI6: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "A0A369MRW6: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "A0A369MHK2: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "A0A369N7Y3: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "D6E7B3: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "A0A369M386: Ammonium Transporter Family [{'start': 9, 'end': 417, 'dc-status': 'CONTINUOUS'}] 424", "A0A3N0AQL8: Ammonium Transporter Family [{'start': 9, 'end': 434, 'dc-status': 'CONTINUOUS'}] 441", "A0A369NYJ2: Ammonium Transporter Family [{'start': 9, 'end': 434, 'dc-status': 'CONTINUOUS'}] 441", "A0A172RYW3: Ammonium Transporter Family [{'start': 9, 'end': 432, 'dc-status': 'CONTINUOUS'}] 439", "A0A1Y3U5V2: Ammonium Transporter Family [{'start': 8, 'end': 417, 'dc-status': 'CONTINUOUS'}] 425", "A0A2S5V2F6: Ammonium Transporter Family [{'start': 7, 'end': 412, 'dc-status': 'CONTINUOUS'}] 417", "A0A8E2QZI6: Ammonium Transporter Family [{'start': 7, 'end': 412, 'dc-status': 'CONTINUOUS'}] 417", "A0A2S5WGI8: Ammonium Transporter Family [{'start': 7, 'end': 412, 'dc-status': 'CONTINUOUS'}] 417", "A0A2S5X1J4: Ammonium Transporter Family [{'start': 7, 'end': 412, 'dc-status': 'CONTINUOUS'}] 417", "A0A2S5WUP6: Ammonium Transporter Family [{'start': 7, 'end': 412, 'dc-status': 'CONTINUOUS'}] 417", "A0A060UWC8: Ammonium Transporter Family [{'start': 15, 'end': 430, 'dc-status': 'CONTINUOUS'}] 475", "G0JRG6: Ammonium Transporter Family [{'start': 15, 'end': 430, 'dc-status': 'CONTINUOUS'}] 475", "A0A257T8W6: Ammonium Transporter Family [{'start': 15, 'end': 434, 'dc-status': 'CONTINUOUS'}] 475", "Q9M6N7: Ammonium Transporter Family [{'start': 22, 'end': 435, 'dc-status': 'CONTINUOUS'}] 475", "A0A8T2FW07: Ammonium Transporter Family [{'start': 22, 'end': 435, 'dc-status': 'CONTINUOUS'}] 475", "Q84KJ7: Ammonium Transporter Family [{'start': 24, 'end': 441, 'dc-status': 'CONTINUOUS'}] 486", "B9SXC7: Ammonium Transporter Family [{'start': 31, 'end': 443, 'dc-status': 'CONTINUOUS'}] 469", "A0A6A6MHQ0: Ammonium Transporter Family [{'start': 33, 'end': 445, 'dc-status': 'CONTINUOUS'}] 470", "Q84KJ6: Ammonium Transporter Family [{'start': 29, 'end': 459, 'dc-status': 'CONTINUOUS'}] 498", "Q2QYV9: Ammonium Transporter Family [{'start': 16, 'end': 438, 'dc-status': 'CONTINUOUS'}] 458", "A0A2K1RA77: Ammonium Transporter Family [{'start': 30, 'end': 454, 'dc-status': 'CONTINUOUS'}] 488", "A0A2K1RA81: Ammonium Transporter Family [{'start': 31, 'end': 455, 'dc-status': 'CONTINUOUS'}] 489", "A0A6A6KHV7: Ammonium Transporter Family [{'start': 28, 'end': 446, 'dc-status': 'CONTINUOUS'}] 474", "A0A6A6KSX7: Ammonium Transporter Family [{'start': 33, 'end': 459, 'dc-status': 'CONTINUOUS'}] 492", "B9SA70: Ammonium Transporter Family [{'start': 32, 'end': 455, 'dc-status': 'CONTINUOUS'}] 489", "B9SWW9: Ammonium Transporter Family [{'start': 22, 'end': 443, 'dc-status': 'CONTINUOUS'}] 477", "A0A059XXR1: Ammonium Transporter Family [{'start': 13, 'end': 421, 'dc-status': 'CONTINUOUS'}] 435", "J9Z839: Ammonium Transporter Family [{'start': 13, 'end': 421, 'dc-status': 'CONTINUOUS'}] 435", "A0A1B9BUU6: Ammonium Transporter Family [{'start': 12, 'end': 420, 'dc-status': 'CONTINUOUS'}] 434", "A0A060URC3: Ammonium Transporter Family [{'start': 12, 'end': 420, 'dc-status': 'CONTINUOUS'}] 434", "A0A7T4WEP4: Ammonium Transporter Family [{'start': 12, 'end': 420, 'dc-status': 'CONTINUOUS'}] 434", "G0JRG9: Ammonium Transporter Family [{'start': 12, 'end': 420, 'dc-status': 'CONTINUOUS'}] 434", "A0A257T7G4: Ammonium Transporter Family [{'start': 12, 'end': 420, 'dc-status': 'CONTINUOUS'}] 434", "A0A257SYX3: Ammonium Transporter Family [{'start': 12, 'end': 421, 'dc-status': 'CONTINUOUS'}] 435", "A0A6A6KH23: Ammonium Transporter Family [{'start': 38, 'end': 452, 'dc-status': 'CONTINUOUS'}] 492", "A0A6A6LR03: Ammonium Transporter Family [{'start': 36, 'end': 450, 'dc-status': 'CONTINUOUS'}] 489", "B9RP82: Ammonium Transporter Family [{'start': 39, 'end': 453, 'dc-status': 'CONTINUOUS'}] 492", "A0A1H5BK12: Ammonium Transporter Family [{'start': 28, 'end': 413, 'dc-status': 'CONTINUOUS'}] 431", "A0A7G5DKA9: Ammonium Transporter Family [{'start': 28, 'end': 413, 'dc-status': 'CONTINUOUS'}] 431", "A0A059XYD5: Ammonium Transporter Family [{'start': 94, 'end': 505, 'dc-status': 'CONTINUOUS'}] 544", "A0A075WG29: Ammonium Transporter Family [{'start': 40, 'end': 448, 'dc-status': 'CONTINUOUS'}] 468", "A0A1G6ABK5: Ammonium Transporter Family [{'start': 12, 'end': 392, 'dc-status': 'CONTINUOUS'}] 403", "A0A248LNW8: Ammonium Transporter Family [{'start': 14, 'end': 393, 'dc-status': 'CONTINUOUS'}] 402", "D9SI36: Ammonium Transporter Family [{'start': 12, 'end': 392, 'dc-status': 'CONTINUOUS'}] 400", "Q608B6: Ammonium Transporter Family [{'start': 45, 'end': 422, 'dc-status': 'CONTINUOUS'}] 433", "A0A0M3A3U0: Ammonium Transporter Family [{'start': 8, 'end': 386, 'dc-status': 'CONTINUOUS'}] 395", "D4XSW0: Ammonium Transporter Family [{'start': 21, 'end': 398, 'dc-status': 'CONTINUOUS'}] 407", "A0A4R8GSH7: Ammonium Transporter Family [{'start': 14, 'end': 396, 'dc-status': 'CONTINUOUS'}] 418", "Q0F2M5: Ammonium Transporter Family [{'start': 10, 'end': 392, 'dc-status': 'CONTINUOUS'}] 403", "A0A5J6WPP9: Ammonium Transporter Family [{'start': 19, 'end': 396, 'dc-status': 'CONTINUOUS'}] 404", "A4BEP1: Ammonium Transporter Family [{'start': 23, 'end': 401, 'dc-status': 'CONTINUOUS'}] 408", "Q2SIR0: Ammonium Transporter Family [{'start': 19, 'end': 396, 'dc-status': 'CONTINUOUS'}] 403", "A0A1E5C7W4: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A2N7L7C8: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A1I5SNU9: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A2G6JLT9: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A7U8C2Y6: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A7R6PPH5: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "R9PMC6: Ammonium Transporter Family [{'start': 19, 'end': 394, 'dc-status': 'CONTINUOUS'}] 400", "Q1Z695: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "Q6LKC8: Ammonium Transporter Family [{'start': 22, 'end': 398, 'dc-status': 'CONTINUOUS'}] 405", "B7WW23: Ammonium Transporter Family [{'start': 12, 'end': 390, 'dc-status': 'CONTINUOUS'}] 400", "A0A8B4RZC4: Ammonium Transporter Family [{'start': 12, 'end': 390, 'dc-status': 'CONTINUOUS'}] 400", "A0A6M3ZKU5: Ammonium Transporter Family [{'start': 12, 'end': 389, 'dc-status': 'CONTINUOUS'}] 400", "A0A1G7UZX2: Ammonium Transporter Family [{'start': 12, 'end': 392, 'dc-status': 'CONTINUOUS'}] 400", "V9UWI2: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A399M359: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0AAE6RA08: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A2N1IV80: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A1H5IPV9: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A7G5DIU4: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A4R7VA58: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A5C4PBE5: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A0H2ZDA1: Ammonium Transporter Family [{'start': 77, 'end': 453, 'dc-status': 'CONTINUOUS'}] 460", "A6V338: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A2R3J3P7: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0AAQ1KFF6: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A1A9K927: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A7Z3BNG6: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A6G6J0F8: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A246FEZ1: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A5R9A082: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "C3V9Z3: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "A0A1H0AH18: Ammonium Transporter Family [{'start': 19, 'end': 395, 'dc-status': 'CONTINUOUS'}] 402", "W0DZX1: Ammonium Transporter Family [{'start': 12, 'end': 390, 'dc-status': 'CONTINUOUS'}] 401", "A0A7T5BFQ2: Ammonium Transporter Family [{'start': 15, 'end': 397, 'dc-status': 'CONTINUOUS'}] 405", "G0JRQ3: Ammonium Transporter Family [{'start': 15, 'end': 397, 'dc-status': 'CONTINUOUS'}] 405", "A0A060UN76: Ammonium Transporter Family [{'start': 15, 'end': 397, 'dc-status': 'CONTINUOUS'}] 405", "A0A257TE48: Ammonium Transporter Family [{'start': 15, 'end': 397, 'dc-status': 'CONTINUOUS'}] 405", "J0S2I0: Ammonium Transporter Family [{'start': 47, 'end': 440, 'dc-status': 'CONTINUOUS'}] 453", "M5U2P1: Ammonium Transporter Family [{'start': 78, 'end': 477, 'dc-status': 'CONTINUOUS'}] 488", "M5SYZ1: Ammonium Transporter Family [{'start': 46, 'end': 445, 'dc-status': 'CONTINUOUS'}] 456", "K5DBA0: Ammonium Transporter Family [{'start': 52, 'end': 456, 'dc-status': 'CONTINUOUS'}] 467", "F2AUF4: Ammonium Transporter Family [{'start': 54, 'end': 458, 'dc-status': 'CONTINUOUS'}] 469", "L7CG99: Ammonium Transporter Family [{'start': 58, 'end': 462, 'dc-status': 'CONTINUOUS'}] 473", "M2ALH9: Ammonium Transporter Family [{'start': 52, 'end': 456, 'dc-status': 'CONTINUOUS'}] 467", "M5S9B4: Ammonium Transporter Family [{'start': 52, 'end': 456, 'dc-status': 'CONTINUOUS'}] 467", "A0A1G6KUG1: Nitrogen regulatory protein P-II [{'start': 487, 'end': 590, 'dc-status': 'CONTINUOUS'}] 601", "A0A1G6KUG1: Ammonium Transporter Family [{'start': 41, 'end': 434, 'dc-status': 'CONTINUOUS'}] 601", "A0A1I2AKI3: Nitrogen regulatory protein P-II [{'start': 487, 'end': 590, 'dc-status': 'CONTINUOUS'}] 601", "A0A1I2AKI3: Ammonium Transporter Family [{'start': 41, 'end': 434, 'dc-status': 'CONTINUOUS'}] 601", "A0AA97D792: Nitrogen regulatory protein P-II [{'start': 477, 'end': 583, 'dc-status': 'CONTINUOUS'}] 593", "A0AA97D792: Ammonium Transporter Family [{'start': 14, 'end': 414, 'dc-status': 'CONTINUOUS'}] 593", "R7QYH5: Nitrogen regulatory protein P-II [{'start': 456, 'end': 561, 'dc-status': 'CONTINUOUS'}] 571", "R7QYH5: Ammonium Transporter Family [{'start': 10, 'end': 399, 'dc-status': 'CONTINUOUS'}] 571", "R6CGI3: Nitrogen regulatory protein P-II [{'start': 455, 'end': 560, 'dc-status': 'CONTINUOUS'}] 570", "R6CGI3: Ammonium Transporter Family [{'start': 10, 'end': 399, 'dc-status': 'CONTINUOUS'}] 570", "A0AA96PW81: Nitrogen regulatory protein P-II [{'start': 454, 'end': 559, 'dc-status': 'CONTINUOUS'}] 569", "A0AA96PW81: Ammonium Transporter Family [{'start': 9, 'end': 398, 'dc-status': 'CONTINUOUS'}] 569", "D3ASW2: Nitrogen regulatory protein P-II [{'start': 454, 'end': 557, 'dc-status': 'CONTINUOUS'}] 568", "D3ASW2: Ammonium Transporter Family [{'start': 8, 'end': 400, 'dc-status': 'CONTINUOUS'}] 568", "A0A396QBZ7: Nitrogen regulatory protein P-II [{'start': 458, 'end': 562, 'dc-status': 'CONTINUOUS'}] 583", "A0A396QBZ7: Ammonium Transporter Family [{'start': 9, 'end': 406, 'dc-status': 'CONTINUOUS'}] 583", "A0A416RXX8: Nitrogen regulatory protein P-II [{'start': 471, 'end': 575, 'dc-status': 'CONTINUOUS'}] 588", "A0A416RXX8: Ammonium Transporter Family [{'start': 11, 'end': 410, 'dc-status': 'CONTINUOUS

In [6]:
# Parse the data from the domain info file into a dictionary keyed by accession number
domain_dict = defaultdict(list)

with Path("domain_info.txt").open() as ifh:    # Using a file context so that everything is closed when we're done
    for line in [_ for _ in ifh.readlines()]:  # Iterating over each line
        accn, data = line.split(": ", 1)       # Get the accession to use as a key, and the data for processing
        loc, name = data.split("]")            # Get the domain name for the text label
        namedata = name.strip().split()        # Split domain name and sequence length
        label, length = " ".join(namedata[:-1]), int(namedata[-1])
        locdata = loc.split(": ")
        start, end = int(locdata[1].split(",")[0]), int(locdata[2].split(",")[0])
        domain_dict[accn].append((start, end, label, length))  # Adds the current motif to a list of motifs

# Visualise the first few lines of content
print(f"{list(domain_dict.items())[:3]=}\n")

# Visualise a multidomain entry
print(f'{domain_dict["Q1Q357"]=}\n')

list(domain_dict.items())[:3]=[('Q8GQS1', [(50, 460, '', 463)]), ('A0A401X433', [(51, 461, '', 465)]), ('A0AAC9SUX5', [(45, 455, '', 459)])]

domain_dict["Q1Q357"]=[(451, 518, '', 679), (11, 408, '', 679), (565, 674, '', 679)]

In [16]:
def result_to_face(domains, fontsize=2):
    """Return a SeqMotifFace, based on the passed UniProt result
    
    LP: We need to make a change here because the result received by the function
        is not the same as in the previous notebook. It's a list of
        (start, end, label, legnth) tuples
    """
    # LP: We can lose most of the prep work here as we did it on parsing
    motifs = []
    for start, end, label, length in domains:
        # seq.start, seq.end, shape, width, height, fgcolor, bgcolor
        if "Ammonium Transporter" in label:   # LP: change here for how we check for a transporter domain
            motifs.append([start, end, "[]", None, 10, "lightblue", "lightblue", f"arial|{fontsize}|white|{label}"])
        else:
            motifs.append([start, end, "[]", None, 10, "black", "red", f"arial|{fontsize}|white|{label}"])
    if len(motifs):
        if length is None:
            return SeqMotifFace(seq=None, motifs=motifs, seq_format="-")
        else:
            return SeqMotifFace(seq="-" * length, motifs=motifs, seq_format="-")
    return None

In [17]:
tree, anno = annotate_tree()  # get clean tree

# Declare tree style
everything = TreeStyle()
everything.show_leaf_name = False
everything.mode = "c"

# One text face for each kingdom
face_dict = {"Eukaryota": TextFace("eukaryota"),
             "Bacteria": TextFace("bacteria"),
             "Archaea": TextFace("archaea")}

# Set colours for kingdoms
colour_dict = {"Eukaryota": "#FFFACD", "Bacteria": "#F0F8FF", "Archaea": "#FFE4E1"}

# Set face colours for kingdoms
colour_dict = {"Eukaryota": "#FFFACD", "Bacteria": "#F0F8FF", "Archaea": "#FFE4E1"}

# Set colours for residue types
# rescolours = {"Y": "#FFCC66", "E": "#009933", "M": "#9966FF"}

# Iterate over leaves
for idx, row in tqdm(anno.iterrows()):
    # Get leaf information
    leaf = row["leaves"]
    # restype = row["first"]
    # fourres = row["four"]    
    kingdomname = row["kingdom"].strip()    
    accn = str(leaf).split()[-1]     # LP: Use the accession to key/query the domain dictionary

    # # Style the leaf node
    # leaf.img_style["bgcolor"] = colour_dict[kingdomname]    
    # leaf.add_face(face_dict[kingdomname], 1, "aligned")

    # # Add gateway residue bubble
    # if restype in ("Y", "E", "M"):
    #     face = CircleFace(radius=20, color=rescolours[restype], style="sphere", label=restype)
    #     face.opacity = 0.3
    #     leaf.add_face(face, 1, position="float")

    # # Add four residues label
    # if len(fourres):
    #     leaf.add_face(TextFace(fourres), 2, position="float")

    # Add motifs/domains
    # LP: Our first change is here - we want to use the leaf's accession number to
    #     query domain_dict
    motifs = result_to_face(domain_dict[accn])
    if motifs is not None:
        leaf.add_face(motifs, 0, "aligned")

tree.render("figure_4.2.pdf", tree_style=everything, w=24, h=24, units="in");

0it [00:00, ?it/s]

In [13]:
tree, anno = annotate_tree()  # get clean tree

# Declare tree style
everything = TreeStyle()
everything.show_leaf_name = False
everything.mode = "c"
tree.show_branch_support = True


tree.ladderize()

face_dict = {"Eukaryota": TextFace("eukaryota"),
             "Bacteria": TextFace("bacteria"),
             "Archaea": TextFace("archaea")}

# Set face colours for kingdoms
colour_dict = {"Eukaryota": "ForestGreen", "Bacteria": "Tan", "Archaea": "IndianRed"}

# Define function symbols
symbols = {"yes": "<    >"}

# Iterate over leaves
for idx, row in anno.iterrows():
    # Get leaf information
    leaf = row["leaves"]
    fused = row["match"]    
    kingdomname = row["kingdom"]   

    # Style the leaf node
    leaf.img_style["bgcolor"] = colour_dict[kingdomname]    
    leaf.add_face(face_dict[kingdomname], 1, "aligned")

    # Add function symbol
    if fused in symbols:
        leaf.add_face(TextFace(symbols[fused], fsize=50), 2, position="float")

tree.render("figure_4.5.pdf", tree_style=everything, w=24, h=24, units="in");